FROM python:3.11-slim

WORKDIR /app

COPY services/ingestion_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/shared ./shared
COPY services/ingestion_service/ .

CMD ["python", "main.py"]
