FROM python:3.11-slim

RUN adduser --disabled-password --gecos '' appuser && \
    pip install --no-cache-dir --upgrade pip

WORKDIR /app

COPY services/ingestion_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache

COPY services/shared ./shared
COPY services/ingestion_service/ .

USER appuser

CMD ["python", "main.py"]
